### ISSUE TITLE
Hey do you have gmail Phishlets?

### ISSUE THREAD

**Issue by devill11100** [syrex1013/EvilGinx3-Phishlets#1]

**Comment by syrex1013** [comment]
No gmail phishlet yet, but there is phishing page for Uadmin in other repo of mine for gmail.

**Comment by devill11100** [comment]
Google uses obfuscated javascript to identify the login as coming from a phishing page. You gotta deobfuscate it and then find a way to bypass it. I have very big problem w it.
 
 but there is phishing page for Uadmin in other repo of mine for gmail. - link?
